version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["b4:f7:e6:2a:36:6d:4e:69:96:4b:8f:b5:43:51:a2:95"]
      - run:
          name: Install dependencies
          command: apk add --update ansible
      - run:
          name: Configure server
          command: ansible-playbook -i inventory main.yml

workflows:
  welcome:
    jobs:
      - welcome/run
  # workflow:
  #   jobs:
  #     - create_infrastructure
  #     - configure_infrastructure
